### ISSUE TITLE
OAuth2.getAccessToken returns invalid accessToken if refreshed

### ISSUE THREAD

**Issue by knownasilya** [google/google-auth-library-nodejs#103]
If the token has expired and you have a refresh token setup, it returns a new access token that only has two parts, i.e. `accessToken.split('.').length === 2`, which results in a JSON parse error when doing:

```js
let split = accessToken.split('.');
let payloadSegment = split[1];
payload = JSON.parse(oauth.decodeBase64(payloadSegment));
```

So in the `getAccessToken` method, the tokens that are returned seem to have an `id_token` which looks more like an accessToken, but that's not accessible since those are returned so I wrote my own version of that method that returns all the tokens.

```js
/**
 * Copy of getAccessToken, but returning all of the tokens
 */
google.auth.OAuth2.prototype.getOrRefreshTokens = function(callback) {
  var credentials = this.credentials;
  var expiryDate = credentials.expiry_date;

  // if no expiry time, assume it's not expired
  var isTokenExpired = expiryDate ? expiryDate <= (new Date()).getTime() : false;

  if (!credentials.access_token && !credentials.refresh_token) {
    return callback(new Error('No access or refresh token is set.'), null);
  }

  var shouldRefresh = !credentials.access_token || isTokenExpired;
  if (shouldRefresh && credentials.refresh_token) {
    if (!this.credentials.refresh_token) {
      return callback(new Error('No refresh token is set.'), null);
    }

    this.refreshAccessToken(function(err, tokens, response) {
      if (err) {
        return callback(err, null, response);
      }     
      if (!tokens || (tokens && !tokens.access_token)) {
        return callback(new Error('Could not refresh access token.'), null, response);
      }     
      return callback(null, tokens, response);
    });   
  } else {
    return callback(null, credentials, null);
  }
};
```

I guess it's possible that I'm using the wrong token, and the access/id tokens need to be used differently? Which token does what and should be used for what purpose?

**Comment by JustinBeckwith** [comment]
Greetings!  These are great questions.  First - I want to share a few samples.  

*[Refreshing Access Tokens](https://github.com/google/google-auth-library-nodejs/blob/master/examples/refreshAccessToken.js)*

This example shows using an OAuth2 workflow to acquire an Access Token and a Refresh Token, and then using the refresh token to acquire a new access token.  

When using `OAuth2Client.request`, we will automatically use the access token you received to create the `Authorization` header for your requests.  

*[Using the OAuth2 Client](https://github.com/google/google-auth-library-nodejs/blob/master/examples/oauth2.js)*


From time to time - the access token will expire.  That's where you use the [code above](https://github.com/google/google-auth-library-nodejs/blob/master/examples/refreshAccessToken.js) to request a new one.  

You shouldn't think of the access token as containing any real information.  The `id_token` is the JWT token that contains all of your claims.  We provide an easy method of verifying the token, and returning the payload for you:

*[Using verifyIdToken](https://github.com/google/google-auth-library-nodejs/blob/master/examples/verifyIdToken.js)*

Since JWT tokens are provided in the clear, it's **super important** that you validate them before trusting any of the information in that id_token.  If you want to just peek into the contents without the `verifyIdToken` step, you could just crack it open like this (not tested):

```js
// do the whole OAuth2 shuffle...
const r = await oAuth2Client.getToken(qs.code);
oAuth2Client.setCredentials(r.tokens);
const idToken = oAuth2Client.credentials.id_token;
const tokenParts = idToken.split('.');
const buf = new Buffer(tokenParts[1], 'base64');
const payload = buf.toString('utf8');
console.log(payload);
```

Or something to that effect :)  Good luck!  And please do let me know if something is unclear, or you run into any trouble.

**Comment by knownasilya** [comment]
@JustinBeckwith I find it rather unclear where the refresh happens, do I need to check that the token expired, or do I always call `refreshAccessToken`?

**Comment by knownasilya** [comment]
@JustinBeckwith the other part is how do i need to send the `id_token` to the client so i can send it back to the server to find the user? Currently I'm saving the `access_token` on the user and only sending back the `access_token` and finding the user via the token. It seems wrong to me, but unsure.

**Comment by MihirLathiya510** [comment]
how about now ? after refreshAccessToken is deprecated and saying use getRequestHeaders instead how should we use it if there is example please share
