### ISSUE TITLE
Use gcp-metadata to talk to the metadata service

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-auth-library-nodejs#190]
We currently have our own code to talk to the metadata service in GCE.  We should use this instead:
https://yarnpkg.com/en/package/gcp-metadata

**Comment by JustinBeckwith** [comment]
I was starting to take a look at this, and I have a few concerns.  The biggest one is that [gcp-metadata](https://github.com/stephenplusplus/gcp-metadata) takes a dependency on [retry-request](https://github.com/stephenplusplus/retry-request), which takes a dependency on [request](https://github.com/request/request). 

Given the amount of work we did to eliminate the request dependency, I'm not excited about adding it back in for basically no user gain. 

@ofrobots @stephenplusplus - what are your thoughts here?  I can think of a few options:
1. We could change gcp-metadata to use Axios instead of request
2. We could just not do this work

Thoughts?

**Comment by ofrobots** [comment]
@stephenplusplus what are your thoughts on dropping the request dependency from `gcp-metadata`?

**Comment by stephenplusplus** [comment]
Well, `request` comes through `retry-request`, and I'd like to leave it there, since by default, that module is intentionally tied to `request`, which I believe is still the most commonly used request module.

If the problem is the size of `request`, then I'd say not doing anything is the most sensible route. If the problem is *using* (as opposed to "loading") the module itself, then you can swap in your preferred request module as an option to `retry-request`. Then, `request` isn't used at all (but it is still downloaded and unpacked from npm).

**Comment by ofrobots** [comment]
In many scenarios, for example, from a security point of view, or from a deployment time point of view, it is the listed dependencies that matter rather than what dependencies actually end up getting loaded. IMO, what gets downloaded is very relevant.

**Comment by JustinBeckwith** [comment]
@stephenplusplus would you mind if I submitted a PR to switch gcp-metadata to use [axios-retry](https://github.com/softonic/axios-retry) instead of request-retry, effectively dropping the gcp specific module's dependency on request?

**Comment by stephenplusplus** [comment]
That'd be great!
