### ISSUE TITLE
Please fix Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by coolgk** [google/google-auth-library-nodejs#315]
https://snyk.io/test/github/google/google-auth-library-nodejs?severity=high&severity=medium&severity=low

thanks.

**Comment by ofrobots** [comment]
This has already been fixed in `node-forge` and snyk needs to update their database. I don't see a place to report this problem to snyk.

From the vulnerability page, note the contradiction: https://snyk.io/vuln/npm:node-forge:20180226. In one place it says `Affecting node-forge package, ALL versions`. Later it says "Remediation
Update node-forge to version 0.7.4 or higher."

/cc @guypod: how do we report bugs in your db?

**Comment by JustinBeckwith** [comment]
👋 Greetings!  We've updated to the latest node-forge, which should be fixed.  I filed this to track synk updating their DB:
https://github.com/snyk/vulnerabilitydb/issues/24

**Comment by karenyavine** [comment]
Hey,
Fixed it in our database, sorry for the inconvenience.  

For future reference, you can update us on any issues in our database at security@snyk.io :)

**Comment by JustinBeckwith** [comment]
Thanks!
