### ISSUE TITLE
Google's 2-step verification

### ISSUE THREAD

**Issue by namelus** [google/google-auth-library-nodejs#368]
Hello all,

Thanks for this lovely module.
I got everything to work, but my account has 2-step verification on it, which requires me to manually input the pin that google sends to my phone.

Can I get around this somehow?

Thanks in advance.

**Comment by JustinBeckwith** [comment]
Greetings!  That shouldn't have an impact on the usage of this library.  If you're using OAuth2, the sign in flow is entirely controlled outside of the library.  After putting in your pin, it should call back to the redirectUrl that comes from your keys.

Can you provide detailed code and repro steps?

**Comment by JustinBeckwith** [comment]
Ah!  It wasn't clear that this was in the context of an e2e with puppeteer.  There's really nothing I can do with this sadly.  If you have MFA enabled on your account, it's always going to ask for that pin.  It's possible you could get *super* fancy and use something like [twilio](http://twilio.com/) to receive the text message to your # in the test, and then try to use puppeteer to enter the pin for you.  That's going to be a lot of moving parts, but not impossible :)

Since this isn't really an issue with the library, I'm going to go ahead and close this out for now.

**Comment by namelus** [comment]
Thanks for the response. 

Can you help clarify a couple terms:
1. e2e - (end to end)
2. MFA - (mobile factor authentication)

Great tip about twilio, I'll check that out.

Thanks again Justin!

**Comment by JustinBeckwith** [comment]
Apologies :) e2e is end to end, and MFA is multi-factor authentication.

**Comment by namelus** [comment]
I feel smarter already

Thanks again 😀

--
Suleman
905-299-6578

sent from mobile
