### ISSUE TITLE
fs.createReadStream throws unhandled exception

### ISSUE THREAD

**Issue by eyqs** [google/google-auth-library-nodejs#395]
In [googleauth.ts](https://github.com/google/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L669), nothing handles errors thrown by `fs.createReadStream`  (for example, when the file doesn't exist), so applications that call `getClient` have to use an unhandled exception handler.

**Comment by JustinBeckwith** [comment]
Interesting!  If I may ask - how did you get into a situation where this happened?  We're actually pretty careful about checking for the file first:
https://github.com/google/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L361

Can you share a repro?

**Comment by ofrobots** [comment]
I think @eyqs is saying that there is no way callers of `fs.createReadStream` can handle errors other than by installing global unhandled rejections handlers.

**Comment by JustinBeckwith** [comment]
Makes sense :) What I'm asking is - how would I even test something like this?  I could add the few lines of code to attach an `.on('error')` handler, and make sure to throw. But...  I actually don't know what situation (short of an invalid file path) would trigger an error in this way since we're checking for the existence of the file first.  

@ofrobots what do you think?

**Comment by ofrobots** [comment]
@eyqs would it be possible for you to put together a test that demonstrates the problem?

**Comment by eyqs** [comment]
Sorry for the delay, and thanks for covering for me, Ali.

Here's a repro:
```
const {google} = require('googleapis');                                                                                                                                                                                                
google.auth.getClient({keyFilename: "invalid_file"}); 
```
The reason is because `getClient` doesn't call `lstat`. I can add a pull request that resolves this, if you'd like.

**Comment by kidplug** [comment]
Why is this issue closed?
As was stated above:

there is no way callers of fs.createReadStream can handle errors other than by installing global unhandled rejections handlers.

Having to catch unhandledRejection / uncaughtException on the outer process object is not an acceptable way for a library to behave.

The caller (calling function) needs to be able to attach a callback function (or receive a Promise), in order to catch authorization failures of all kinds.
see: https://github.com/googleapis/nodejs-speech/issues/285

**Comment by kidplug** [comment]
@eyqs I think there are lots of spots in the getClient() logic that are not catching exceptions (or checking for rejected Promises perhaps).

**Comment by JustinBeckwith** [comment]
Greetings!  If you can provide a small code snippet that demonstrates the unhandled exceptions y'all are running into, it would be super helpful.

Would you mind creating a new issue with the code snippet and the exception?

**Comment by kidplug** [comment]
sounds like the issue is understood and being discussed here
https://github.com/googleapis/gapic-generator/issues/2065
