### ISSUE TITLE
how to skip sign-in UI which is presented by Google authorization endpoint?

### ISSUE THREAD

**Issue by kutlaykural** [google/google-auth-library-nodejs#406]
Hi everyone,

Is there anyway to reach an application web server without seeing google auth prompt? 
Maybe with setting necessary parameters to url like;

https://accounts.google.com/o/oauth2/v2/auth?client_id=YOUR_CLIENT_ID&mail=YOUR_MAIL&password=YOUR_PASSWORD&redirect_to=YOUR_WEB_SITE

expected result:
seeing my site(YOUR_WEB_SITE) without prompt but authenticated

Best,

**Comment by JustinBeckwith** [comment]
Greetings!  This is not something we can provide.  One of the ideas behind `OAuth2` in general is that the user should never enter their username and password in external applications that could cache, or otherwise mishandle them.  When a user provides their password, it should *always* be on the Google specific consent screen.  

Depending on what you're trying to do, using service account credentials may be a better path :)

Can you share some details on what you're trying to do?

**Comment by kutlaykural** [comment]
Google auth provider is nightmare of automated test scripts. To login web application without seeing google login screen but right paramethers is not easy.  If there is any way to skip login prompt can you explain it? Setting http request url paramethers was the first way came to my mind.

**Comment by kutlaykural** [comment]
Do you still need more info?

**Comment by JustinBeckwith** [comment]
Got it!  You cannot skip the login prompt, but I *do* have an example of using [puppeteer](https://github.com/GoogleChrome/puppeteer) to automate it using tests :)

https://github.com/google/google-auth-library-nodejs/blob/master/examples/puppeteer/oauth2-test.js

Hope this helps!

**Comment by rob4629** [comment]
Hey,

The above link no longer appears to work. I can understand your reasons for not allowing a user to skip the prompt... but can you provide a clear example of how we can automate the "Log in with Google" option for our own sites?

When running tests as part of our CI, our login attempts are being flagged as suspicious (rightly so), due to the login attempt originating from a different location to where the account was set up. I think a number of people would find it beneficial to be able to log in as a "Test User", which could allow us to ignore / by-pass the suspicious activity warning. -- Either as an API request, or with some way of flagging a Google Account as a test account.

Is this possible?

**Comment by rob4629** [comment]
This might be the correct link -> https://github.com/googleapis/google-auth-library-nodejs/blob/master/samples/puppeteer/oauth2-test.js

**Comment by rob4629** [comment]
> Got it! You cannot skip the login prompt, but I _do_ have an example of using [puppeteer](https://github.com/GoogleChrome/puppeteer) to automate it using tests :)
> 
> https://github.com/google/google-auth-library-nodejs/blob/master/examples/puppeteer/oauth2-test.js
> 
> Hope this helps!

Hi Justin,

We don't use SSO on our project, and so the steps mentioned in the oauth2-test file haven't resolved my issue sadly. My issue is that when our tests run overnight as part of our CI, in a location. This causes the Google Suspicious Activity warning to trigger. Is there a way for us to pass cookies, or set some value so that this warning isn't triggered?
