### ISSUE TITLE
generateAuthUrl() generated url always asks for offline access

### ISSUE THREAD

**Issue by Cir0X** [google/google-auth-library-nodejs#74]
the `generateAuthUrl()` method generatates thee different urls for me, which differs from the `access_type` parameter

with `access_type = 'online'`:

```
https://accounts.google.com/o/oauth2/auth?access_type=online&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&response_type=code...
```

with `access_type = 'offline'`:

```
https://accounts.google.com/o/oauth2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&response_type=code...
```

and without `access_type` (according to this [example](https://github.com/google/google-api-nodejs-client/blob/master/README.md#generating-an-authentication-url) it should defaults to online):

```
https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&response_type=code...
```

Regardless of the url, there is always a prompt asking for offline access.

The version of the library I've used: `0.9.6`

The code I've used to generate the url:

``` javascript
var url = oauth2Client.generateAuthUrl({
    access_type: 'online',
    scope: 'https://www.googleapis.com/auth/userinfo.profile'
});
```

**Comment by murgatroid99** [comment]
According to the [OpenID documentation](https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters), access_type is optional and if it is absent, the server behaves as though it was "offline", which is exactly the behavior that the example indicates.

What is this "prompt asking for offline access"? I don't see anything like that in this library.

**Comment by Cir0X** [comment]
This prompt from google:
![](http://i.stack.imgur.com/MmGyI.jpg)


It seems that this only occurs, when my `redirect_uri` is `localhost`.

**Comment by JustinBeckwith** [comment]
Greetings @Cir0X!  I'm having a little trouble reproducing this one.  I am using the example here:
https://github.com/google/google-auth-library-nodejs/blob/next/examples/oauth2.js

I changed the sample to use this for url generation, and even tried to force the consent dialog:

```js
// Generate the url that will be used for the consent dialog.
const authorizeUrl = oAuth2Client.generateAuthUrl({
  access_type: 'offline',
  scope: [
    'https://www.googleapis.com/auth/userinfo.profile',
    'https://www.googleapis.com/auth/devstorage.read_write',
    'https://www.googleapis.com/auth/plus.me',
    'https://www.googleapis.com/auth/compute'
  ],
  prompt: 'consent select_account'
});
```

This generates a consent dialog, but nowhere does it ask me if I should allow offline access:

![image](https://user-images.githubusercontent.com/534619/34315037-07f52a28-e730-11e7-9638-099193f95818.png)

Note, my `redirect_uri` is set to `localhost:3000`.   I am also using the alpha npm release of our 1.0 library, which you can try out at `npm install google-auth-library@1.0.0-alpha.1`.

Given that this issue is nearly a year old, I'm going to go ahead and close it out.  if you can include detailed instructions on how to reproduce it - I'd be happy to take a look :)
